subunit_gearman_server: logstash.openstack.org
# For every file found in the logs directory (and its subdirs), the
# module will attempt to match the filenames below.  If there is a
# match, the file is submitted to the subunit processing queue, along
# with the tags for that match.  The first match wins, so be sure to
# list more specific names first.  The names are un-anchored regular
# expressions (so if you need to match the root (i.e, the work/logs/
# directory), be sure to anchor them with ^).
subunit_processor_config:
  files:
    - name: testrepository.subunit
    - name: karma.subunit
