- name: Write root marker if zuul.branch
  when: "zuul.branch is defined"
  copy:
    dest: "{{ root_marker_dir }}/.root-marker"
    content: "Project: {{ zuul.project.name }} Branch: {{ zuul.branch }} Build: {{ zuul.build }} Revision: {{ zuul.ref }}"
    mode: 0644
- name: Write root marker if zuul.tag
  when: "zuul.tag is defined"
  copy:
    dest: "{{ root_marker_dir }}/.root-marker"
    content: "Project: {{ zuul.project.name }} Tag: {{ zuul.tag }} Build: {{ zuul.build }} Revision: {{ zuul.ref }}"
    mode: 0644
