- hosts: localhost
  tasks:
    - name: Add bridge.o.o to inventory
      add_host:
        name: bridge.eco.tsi-dev.otc-service.com
        ansible_python_interpreter: python3
        ansible_user: zuul
        # Without setting ansible_host directly, mirror-workspace-git-repos
        # gets sad because if delegate_to localhost and with add_host that
        # ends up with ansible_host being localhost.
        ansible_host: bridge.eco.tsi-dev.otc-service.com
        ansible_port: 22

- hosts: localhost
  tasks:
    - name: Add bridge.o.o hostkey to known hosts
      known_hosts:
        name: bridge.eco.tsi-dev.otc-service.com
        key: "bridge.eco.tsi-dev.otc-service.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDz1V3sQhj7f7g7At4nTJxVYHe/v4/26cNiwjjS8j38cTc62aLjlZgE3Axw5va9S4L+6+SVNZZTlhd2qNa0ND0XO0x39hHcm8cPfzz5JYLvYTYebl3ZtdX37QVvN36ubmaOiyWCL9KLAH/6Tdf414PNa8UOAKSAdO5I407aSPi0t4zaS/Kk9VheUOJe7sPjCE4kwqH8Bt+Je2LPYtUlL+65ukUXd80Gu5tdOXQzLbdPDkdhn7oxqNudhnFW63gjKx0C4RarG/pbFLlEpvrn1yxI4AmCso32OwKRUDsA6RL4ENNMaXf/lvjP/+y6lthX8E0UvcwckR9MifwUKOJTtZ2zJJMen9hxNmjqWGjCvT2/eUvOuLEoRpfNLYQU3UNt6FPp5g/N88AHw9MApdYTBNve7bDFPmejnAO8FZA8y35CspLsT8FMTraV+RH0AoRihNAIqWOxHmaoMt+fOMX1DbBLbGtIo8HeCEEILUSdmDNAVzVpBi3iVJSx6s7vV2NcYHE="

- hosts: bridge.eco.tsi-dev.otc-service.com
  tasks:
    - name: "Make sure a manaul maint isn't going on"
      wait_for:
        path: /home/zuul/DISABLE-ANSIBLE
        state: absent
        sleep: 10
        timeout: 3600 # Wait for an hour before bailing

    - name: "Correct ownership of repos"
      command: "chown -R zuul:zuul /home/zuul/src"
      # E303: Skip linting since it triggers on the "chown" command,
      # but we prefer the shell above
      tags:
        - skip_ansible_lint
      # Ignore the error if the dir doesn't exist
      ignore_errors: true
      # Do this as root, because it needs to chown root-owned files
      become: true

    # This role executes code on the executor, so this needs to be in
    # a trusted playbook.
    - name: Synchronize src repos to workspace directory.
      include_role:
        name: prepare-workspace-git
