- hosts: localhost
  tasks:
    - name: Add bridge to inventory
      add_host:
        name: bridge.eco.tsi-dev.otc-service.com
        ansible_python_interpreter: python3
        ansible_user: zuul
        # Without setting ansible_host directly, mirror-workspace-git-repos
        # gets sad because if delegate_to localhost and with add_host that
        # ends up with ansible_host being localhost.
        ansible_host: bridge.eco.tsi-dev.otc-service.com
        ansible_port: 22

- hosts: localhost
  tasks:
    - name: Add bridge hostkey to known hosts
      known_hosts:
        name: bridge.eco.tsi-dev.otc-service.com
        key: "bridge.eco.tsi-dev.otc-service.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyDSScTpfAgr76+NMsCSgYM/Tdpp1O16lqXSLd2pCBKQSHKMzj79QtxFcskG9yLCnajh85vOd1a29+MIGQuujm+dNa7tfiYacOL9U2csMWUgNzR2pYTYjF1ntnLyRNuuZ/mGiaUuXtsSF6TRuVZg1/Rqa8pUIQj/sdzp54EivBPoneTvEum2MwSLTbExnNAhZC/97Qp45GHM1JozVr8Y/03ZGarse2MXrI0P8sygnimBzwhl1pIrGK4HHCOtAns0A498a2R70NuSm1VesUbex3CCCp/p58l5pQR68S+noFW273dPCy4rcE11ijgtSZflknRe2+VVf8QacQ81upCDAZ"

- hosts: bridge.eco.tsi-dev.otc-service.com
  tasks:
    - name: "Make sure a manaul maint isn't going on"
      wait_for:
        path: /home/zuul/DISABLE-ANSIBLE
        state: absent
        sleep: 10
        timeout: 3600 # Wait for an hour before bailing

    - name: "Correct ownership of repos"
      command: "chown -R zuul:zuul /home/zuul/src"
      # E303: Skip linting since it triggers on the "chown" command,
      # but we prefer the shell above
      tags:
        - skip_ansible_lint
      # Ignore the error if the dir doesn't exist
      ignore_errors: true
      # Do this as root, because it needs to chown root-owned files
      become: true

    # This role executes code on the executor, so this needs to be in
    # a trusted playbook.
    - name: Synchronize src repos to workspace directory.
      include_role:
        name: prepare-workspace-git
