- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - otc-tox-linters:
            required-projects: zuul/zuul-jobs
    gate:
      jobs:
        - otc-tox-linters:
            required-projects: zuul/zuul-jobs
