- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - otc-tox-linters: &otc-tox-linters-vars
            required-projects:
              - zuul/zuul-jobs
              - opentelekomcloud-infra/otc-zuul-jobs
    gate:
      jobs:
        - otc-tox-linters: *otc-tox-linters-vars
