- name: Set config file
  set_fact:
    virtualenv_config_file: '{{ ansible_env.HOME }}/.config/virtualenv/virtualenv.ini'

- name: Ensure config directory
  file:
    path: '{{ virtualenv_config_file | dirname }}'
    state: directory
    mode: 0755

# NOTE(ianw) : 2020-03-27 workaround 46.1.1 broken setuptools
#  https://github.com/pypa/virtualenv/issues/1752
- name: Add download flag, to not use vendorded versions of setuptools/pip
  ini_file:
    path: '{{ virtualenv_config_file }}'
    section: 'virtualenv'
    option: download
    value: 'True'
    mode: '0644'
